### ISSUE TITLE
Error occuring while running makefile

### ISSUE THREAD

**Issue by Debajyati** [sammaji/chess#1]
## The Situation
![image](https://github.com/user-attachments/assets/4de78d6e-9f7a-48f3-8efe-5056f150a655)

## Steps to reproduce
```bash
$ git clone https://github.com/sammaji/chess
```
```bash
$ cd chess
```
```bash
$ make all
```
## System:
Void Linux WSL

**Comment by sammaji** [comment]
It's happening because the math module is not getting linked. Let me see if I can fix this.
